### PR TITLE
upgrade dependencies initial

### PR DESCRIPTION
**Pull request by pedrogh**
This upgrades Rustler and will upgrade pact_mock_server.

### CODE REVIEW

**Comment by elitau** [comment]
Are the tests green for you?

I get the [following output](https://gist.github.com/elitau/dea2c37a9cf1d0a90a465d131a8cf3e4) when running `mix test`.

Also just I've recognized that travis-CI.org stopped its service. I'll try to move it to a working CI Service in the near future.

**Comment by pedrogh** [comment]
Tests are not green.

Yesterday the tests were segfaulting.  Now they're failing like [this](https://gist.github.com/pedrogh/5c7a8ada1bbcf061d1de14d7b218f623).

**Comment by elitau** [comment]
> Tests are not green.
> 
> Yesterday the tests were segfaulting. Now they're failing like [this](https://gist.github.com/pedrogh/5c7a8ada1bbcf061d1de14d7b218f623).

The error
`This BEAM file was compiled for a later version of the run-time system than 22.
  To fix this, please recompile this module with an 22 compiler.`
can be fixed by cleaning your build artifacts and recompiling the project, eg. by deleting the _build folder.

**Comment by pedrogh** [comment]
Yes, thank you!
I just got the tests running w/o segfaulting earlier this morning by doing just what you suggested just now.  Thank you

Now working to see what is going on with the tests that fail.

State of tests passing/failing is now:
./test/interaction_test.exs - pass
./test/request_test.exs  - pass
./test/term_test.exs  - pass
./test/a_test.exs  - pass
./test/mock_server/pact_mock_server_test.exs 
./test/mock_server/mock_server_supervisor_test.exs - fail
./test/mock_server/rust_mock_server_facade_test.exs - fail
./test/pact_elixir_test.exs  - pass
./test/dsl_integration_test.exs - fail
./test/pact_specification/version_2_0_test.exs  - pass
./test/service_provider_test.exs  - pass
./test/termdetector_test.exs  - pass
./test/response_test.exs  - pass
./test/errors_test.exs  - pass

**Comment by elitau** [comment]
Seems like the result from the Rust functions has changed. Previously most of the functions returned a Tuple like `{:ok, result}` or `{:error, result}`. Now they only return the `result`, eg. 
```
13) test create_mock_server fails if mock server could not start due to broken json (PactElixir.RustPactMockServerFacadeTest)
     test/mock_server/rust_mock_server_facade_test.exs:44
     match (=) failed
     code:  assert {:error, :invalid_pact_json} = RustPactMockServerFacade.create_mock_server(broken_json, @port)
     left:  {:error, :invalid_pact_json}
     right: :invalid_pact_json
     stacktrace:
       test/mock_server/rust_mock_server_facade_test.exs:47: (test)
```

Did you change the return value in the functions or has the new version of the rust mock_server library changed the return value?

**Comment by elitau** [comment]
Looks good to me. I would merge the PR (if you convert it to a usual PR) and fix the [deprecations](https://github.com/rusterlium/rustler/blob/master/CHANGELOG.md#deprecations) coming with rustler 0.22.

**Comment by pedrogh** [comment]
Was going to say: In order to get the tests to run one might have to run `ulimit -n xxxx` but I am glad the tests run on your machine.

On my machine in order for the test to run i need to run `ulimit -n xxxx`, where xxxx =  2048, or I get an error "Too many open files".
I read that one can configure rust to limit the number of threads/processes? to avoid that error but I am not sure how to do that yet.

**Comment by elitau** [comment]
@pedrogh I've never encountered the error "Too many open files" on my Mac OS machine.

**Pull request merged**
