### PR TITLE
Feature/add regex matching

### PR DESCRIPTION
**Pull request by SirObi**
Implements Pact::Term for Elixir.
This is in line with the guidelines at https://docs.pact.io/getting_started/matching#regular-expressions

>You want to be as loose as possible with the matching for the response (will_respond_with(...)). This stops the tests being brittle on the provider side. 

This will allow for the following syntax when writing a test case:
`will_respond_with(status: 200, body: %{status: "ok", score: %Term{generate: 0.98, regex: "[0-9]*.[0-9]+"}})`

Using the word "regex" instead of "matcher" in the test case, as it seems easier to comprehend (based on my attempts to explain Pact to other devs).

Does not break the current implementation of `Response.new`:

`iex> PactElixir.Response.new()` still returns the correct defaults:
`iex> %PactElixir.Response{body: "", headers: %{}, status: 200}`

`TermDetector` detects `PactElixir.Term` in nested maps recursively - this is consistent with other implementations of Pact.

### CODE REVIEW

**Comment by SirObi** [comment]
hmm, coverage went down - will add some tests for `Term` and `TermDetector` tomorrow

**Comment by elitau** [comment]
Great work. Thanks for the new feature.

**Comment by elitau** [comment]
@SirObi I just had another look at this and noticed that this seems to be a deprecated solution (putting `json_class` directly into the values in the pact file).
Would it break your tests if I would switch to the newer [Matching Rules](https://github.com/pact-foundation/pact-specification/tree/version-2#matching-rules) introduced in Version 2 of the pact specification?

**Comment by SirObi** [comment]
@elitau not at all - I guess we can always use the old version until we adapt to the change.
Since I'm leaving the current company, I'll let our Elixir guys know to expect it.
Thanks for the heads-up!

**Pull request merged**
